@startuml
'https://plantuml.com/sequence-diagram

mainframe sd AddPromotion
autoactivate on

participant ":PromotionCommand" as PromotionCommand
participant "<<class>>\nPromotionlist" as Promotionlist
participant TextUi
participant "<<class>>\nItemlist" as Itemlist
participant "<<class>\n Promotion" as Promotion

PromotionCommand -> Promotionlist : addPromotion(promotion)
Promotionlist -> Itemlist : isItemExist(itemName)
Itemlist --> Promotionlist : isExists
Promotionlist -> Promotionlist : itemIsOnPromo(itemName)
return notOnPromo
Promotionlist -> Promotionlist : isValidDiscount()
return isValid
Promotionlist -> Promotionlist : isValidMonth()
return isValid
Promotionlist -> Promotionlist : isValidTime()
return isValid
Promotionlist -> Promotionlist : isValidDuration()
return isValid
Promotionlist -> Promotion : add(promotion)
Promotion --> Promotionlist
Promotionlist -> TextUi : print(AddPromotion)
TextUi --> Promotionlist
Promotionlist --> PromotionCommand

@enduml