@startuml
!include ../Style.puml

participant ":BestsellerCommand" as BestsellerCommand
participant ":Cashier" as Cashier
participant ":TextUi" as TextUi

BestsellerCommand -> Cashier: getBestseller()
activate Cashier
Cashier -> Cashier: Retrieve bestseller
Cashier --> BestsellerCommand: itemName
deactivate Cashier
BestsellerCommand -> TextUi: replyToUser("The current best-selling item is {itemName}")

@enduml