@startuml
!include ../Style.puml

participant BestsellerCommand
participant Cashier
participant TextUi

BestsellerCommand -> Cashier: getBestseller()
activate Cashier
Cashier -> Cashier: Retrieve bestseller
Cashier --> BestsellerCommand: Bestselling item
deactivate Cashier
BestsellerCommand -> TextUi: replyToUser("The current best-selling item is {bestseller.getItemName()}")

@enduml