@startuml

skinparam classFontColor automatic

class Cashier #MistyRose {
    - transactions: ArrayList<Transaction>
    + addItem(transaction: Transaction): void
    + getTransactions(): ArrayList<Transaction>
    + getTransactions(item: Item): ArrayList<Transaction>
    + getTransaction(index: int): Transaction
    + getTotalRevenue(): float
    + getTotalProfit(): float
    + getBestseller(): Item
}

class Transaction {
    - dateTime: String
    - totalPrice: float
    - profit: float
    - item: String
    - quantity: int
    - buyPrice: float
    - sellPrice: float

    + Transaction(String, int, float, float)
    + Transaction(String, int, float, float, String)
}

class Item {
    + isMark: boolean
    + isOOS: boolean
    - itemName: String
    - quantity: int
    - unitOfMeasurement: String
    - category: String
    - buyPrice: float
    - sellPrice: float
    +Item(String, int, String, String, float, float)
}

Cashier --> Transaction : has 1..* transactions
Transaction --> Item : has 1 item

hide circle
skinparam classAttributeIconSize 0
@enduml