@startuml
!include ../Style.puml

participant ":TotalProfitCommand" as TotalProfitCommand
participant ":Cashier" as Cashier
participant ":TextUi" as TextUi


mainframe sd
alt get total revenue
    TotalProfitCommand -> Cashier: getTotalRevenue()
    activate Cashier
    Cashier -> Cashier: Calculate total revenue
    Cashier --> TotalProfitCommand: totalRevenue
    deactivate Cashier
    TotalProfitCommand -> TextUi: replyToUser("You have earned {totalRevenue} in revenue so far.")
else get total profit
    TotalProfitCommand -> Cashier: getTotalProfit()
    activate Cashier
    Cashier -> Cashier: Calculate total profit
    Cashier --> TotalProfitCommand: totalProfit
    deactivate Cashier
    TotalProfitCommand -> TextUi: replyToUser("You have earned {totalProfit} in profits so far.")
end

@enduml