@startuml
participant TotalProfitCommand
participant Cashier
participant TextUi

TotalProfitCommand -> Cashier: getTotalProfit() / getTotalRevenue()
activate Cashier
Cashier -> Cashier: Calculate total profit / total revenue
Cashier --> TotalProfitCommand: totalProfit / totalRevenue
deactivate Cashier
TotalProfitCommand -> TextUi: replyToUser("You have earned {totalProfit} in {profits/revenue} so far.")

@enduml