@startuml
!include ../Style.puml

actor User
participant ":Parser" as Parser
participant ":AddCommand" as AddCommand
participant ":Itemlist" as Itemlist
participant ":EditCommand" as EditCommand

User -> Parser: add command
activate Parser

Parser -> AddCommand: prepareAdd(userInput)
activate AddCommand
activate Itemlist
alt Item exists
    AddCommand -> EditCommand: edit Item
    activate EditCommand
    EditCommand -> Itemlist: editQuantity(index, newQuantity)
    deactivate EditCommand
    Itemlist --> AddCommand
    AddCommand -> User: Output success message
else Item does not exist
    AddCommand -> Itemlist: addItem(item)
    Itemlist --> AddCommand

AddCommand -> User: Output success message
deactivate AddCommand
end
deactivate Itemlist
deactivate Parser
@enduml
