@startuml
actor User
participant "ListCommand :ListCommand" as LC
participant "UI :TextUi" as UI
participant "ItemList :Itemlist" as IL

User -> LC : execute()
activate LC

LC -> IL : isEmpty()
activate IL
IL --> LC : false
deactivate IL

alt category equals "NA" and not isListMarked
    LC -> UI : showList(itemList)
    activate UI
    UI --> LC
    deactivate UI
else category not equals "NA" and not isListMarked
    LC -> UI : showCustomizedList(itemList, category, false)
    activate UI
    UI --> LC
    deactivate UI
else category equals "NA" and isListMarked
    LC -> UI : showCustomizedList(itemList, "NA", true)
    activate UI
    UI --> LC
    deactivate UI
else
    LC -> UI : showCustomizedList(itemList, category, true)
    activate UI
    UI --> LC
    deactivate UI
    deactivate LC
end

hide footbox
@enduml
