@startuml
participant BestsellerCommand
participant TotalProfitCommand
participant Cashier
participant TextUi

BestsellerCommand -> Cashier: getBestseller()
activate Cashier
Cashier -> Cashier: Retrieve bestseller
Cashier --> BestsellerCommand: Bestselling item
deactivate Cashier
BestsellerCommand -> TextUi: replyToUser("The current best-selling item is {bestseller.getItemName()}")

TotalProfitCommand -> Cashier: getTotalProfit() / getTotalRevenue()
activate Cashier
Cashier -> Cashier: Calculate total profit / total revenue
Cashier --> TotalProfitCommand: totalProfit / totalRevenue
deactivate Cashier
TotalProfitCommand -> TextUi: replyToUser("You have earned {totalProfit} in {profits/revenue} so far.")

@enduml