@startuml
!include ../Style.puml
'https://plantuml.com/sequence-diagram

mainframe sd DeletePromotion

participant ":PromotionCommand" as PromotionCommand
participant ":Promotionlist" as Promotionlist
participant ":TextUi" as TextUi

alt item has an ongoing promotion
    PromotionCommand -> Promotionlist : getPromotion(itemName)
    Promotionlist --> PromotionCommand : promotion
    PromotionCommand -> Promotionlist : getIndex(promotion)
    Promotionlist --> PromotionCommand : index
    PromotionCommand -> Promotionlist : deletePromotion(index)
    PromotionCommand -> TextUi : print(deletePromotion)
else item does not have any promotion
    PromotionCommand -> TextUi : print(ITEM_NOT_ON_PROMO)
end

hide footbox
@enduml