@startuml
!include ../Style.puml
'https://plantuml.com/sequence-diagram

participant ":PromotionCommand" as PromotionCommand
participant ":Promotionlist" as PromotionList
participant ":TextUi" as TextUi
participant ":Itemlist" as Itemlist
participant ":Promotion" as Promotion


-> PromotionCommand: execute()

alt if user wants to create a promotion
    ref over PromotionCommand, PromotionList, Itemlist, Promotion, TextUi : AddPromotion
else if user wants to delete a promotion
    ref over PromotionCommand, PromotionList, TextUi : DeletePromotion
else if user wants to list all promotions
    PromotionCommand -> TextUi: printPromotion()
else if user enters invalid command
end

<-- PromotionCommand

hide footbox
@enduml